# Generated by Django 4.2.9 on 2024-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('s_content', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
