# Generated by Django 4.2.9 on 2024-03-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('blog_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogHome.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('reply', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogHome.comments')),
            ],
        ),
    ]
