# Generated by Django 5.0.4 on 2024-04-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0005_remove_blog_name_remove_comments_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='Full_content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='s_content',
            new_name='content_in_short',
        ),
    ]
